#!/bin/bash


# Argument validation

if [ "$#" -eq 0 ];then
	echo "No arguments provided."
	echo "Usage: $0 <IP> <Filename_to_write>"
	exit 1

elif [ -z $2 ];then
	echo "Usage: $0 <IP> <Filename_to_write>"
	exit 1

else
	echo "[+] Starting nmap scan..."
fi

# Main code

nmap -sV -sC -A -O -p- --defeat-rst-ratelimit -sS $1 -oN $2

