#!/bin/bash

# Takes just two arguments and passes them to nmap so you dont have to type the whole thing
# Argument validation
if [ "$#" -eq 0 ];then
	echo "No arguments provided."
	echo "Usage: $0 <IP> <Filename_to_write>"
	exit 1

elif [ -z $2 ];then
	echo "Usage: $0 <IP> <Filename_to_write>"
	exit 1

else
	echo "[+] Starting nmap scan..."
fi

# Main code
nmap -sV -sC -A -O -p- --defeat-rst-ratelimit -sS $1 -oN $2

